# Generated by Django 4.0.3 on 2022-04-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
