# Generated by Django 3.2.10 on 2022-05-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0004_remove_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('isSubscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
