# Generated by Django 3.2.10 on 2022-08-01 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_name_contact_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='name',
        ),
    ]
