# Generated by Django 3.2.10 on 2022-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_username_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=250),
        ),
    ]
